create extension if not exists pgcrypto;
create table users (id uuid primary key default gen_random_uuid(), email text not null unique, password_hash text, display_name text not null, created_at timestamptz not null default now());
create table auth_identities (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, provider text not null check (provider in ('password','google','apple')), provider_subject text not null, unique(provider, provider_subject));
create table couples (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now());
create table couple_members (couple_id uuid not null references couples(id) on delete cascade, user_id uuid not null references users(id) on delete cascade, primary key (couple_id, user_id));
create table invitations (id uuid primary key default gen_random_uuid(), couple_id uuid not null references couples(id) on delete cascade, created_by uuid not null references users(id), token_hash text not null unique, expires_at timestamptz not null, accepted_at timestamptz);
create table consents (id uuid primary key default gen_random_uuid(), couple_id uuid not null references couples(id) on delete cascade, user_id uuid not null references users(id), scope text not null, granted_at timestamptz, expires_at timestamptz, revoked_at timestamptz);
create table messages (id uuid primary key default gen_random_uuid(), couple_id uuid not null references couples(id) on delete cascade, sender_id uuid not null references users(id), kind text not null check (kind in ('normal','encrypted','time_capsule')), ciphertext text not null, key_envelope text, unlock_at timestamptz, created_at timestamptz not null default now());
create table shared_events (id uuid primary key default gen_random_uuid(), couple_id uuid not null references couples(id) on delete cascade, title text not null, starts_at timestamptz not null, ends_at timestamptz, notes text, created_by uuid not null references users(id), created_at timestamptz not null default now());
