import * as Location from 'expo-location';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { api } from '../src/services/api';
import { encryptWithPassphrase } from '../src/services/crypto';
import { theme } from '../src/theme';

type Feature = 'music'|'events'|'ratings'|'check-in'|'activities'|'location'|'wellbeing';
const copy:Record<Feature,{icon:string;title:string;subtitle:string}>={music:{icon:'🎵',title:'موسیقی مشترک',subtitle:'موسیقی را با هم نگه دارید.'},events:{icon:'📅',title:'رویدادهای مشترک',subtitle:'لحظه‌ی بعدی را در تقویم نگه دارید.'},ratings:{icon:'✦',title:'نبض رابطه',subtitle:'بازخورد متعادل، نه حکم.'},'check-in':{icon:'🧠',title:'گفت‌وگوی دوره‌ای',subtitle:'سوال‌های کوتاه برای گفت‌وگوی بهتر.'},activities:{icon:'✨',title:'ایده‌های قرار',subtitle:'چیزی پیدا کنید که هر دو دوست دارید.'},location:{icon:'📍',title:'موقعیت مکانی',subtitle:'فقط با رضایت و زمان انقضا.'},wellbeing:{icon:'🌷',title:'همراهی چرخه‌ای',subtitle:'خصوصی، اختیاری و جدا از امتیاز رابطه.'}};
type EventRow={id:string;title:string;starts_at:string};
export default function FeatureScreen(){ const raw=useLocalSearchParams<{feature?:string}>().feature; const feature=(raw&&raw in copy?raw:'events') as Feature; const meta=copy[feature]; const [enabled,setEnabled]=useState(false); const [input,setInput]=useState(''); const [score,setScore]=useState(0); const [items,setItems]=useState<EventRow[]>([]); const [busy,setBusy]=useState(false);
 useEffect(()=>{ if(feature==='events') api<{events:EventRow[]}>('/v1/events').then(r=>setItems(r.events)).catch(()=>{}); },[feature]);
 const action=async()=>{ if(busy)return; setBusy(true); try{
   if(feature==='events'){ if(!input.trim())throw new Error('عنوان رویداد را وارد کن'); const startsAt=new Date(Date.now()+24*60*60*1000).toISOString(); await api('/v1/events',{method:'POST',body:JSON.stringify({title:input.trim(),startsAt})}); setInput(''); const r=await api<{events:EventRow[]}>('/v1/events'); setItems(r.events); }
   else if(feature==='ratings'){ if(!score)throw new Error('یک امتیاز انتخاب کن'); await api('/v1/ratings',{method:'POST',body:JSON.stringify({score,category:'overall'})}); Alert.alert('ثبت شد','بازخوردت ذخیره شد.'); }
   else if(feature==='activities'){ if(!input.trim())throw new Error('یک ایده بنویس'); await api('/v1/activities',{method:'POST',body:JSON.stringify({title:input.trim(),tags:['couple']})}); setInput(''); Alert.alert('ذخیره شد','ایده به فضای مشترک اضافه شد.'); }
   else if(feature==='location'){ const permission=await Location.requestForegroundPermissionsAsync(); if(permission.status!=='granted')throw new Error('مجوز موقعیت داده نشد'); const position=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced}); const expiresAt=new Date(Date.now()+60*60*1000).toISOString(); await api('/v1/consents',{method:'POST',body:JSON.stringify({scope:'location',expiresAt})}); await api('/v1/location/share',{method:'POST',body:JSON.stringify({latitude:position.coords.latitude,longitude:position.coords.longitude,accuracyM:position.coords.accuracy??undefined,expiresAt})}); setEnabled(true); Alert.alert('موقعیت فعال شد','اشتراک‌گذاری برای یک ساعت فعال است.'); }
   else if(feature==='wellbeing'){ if(input.length<8)throw new Error('برای رمزگذاری داده حداقل یک رمز ۸ کاراکتری وارد کن'); const encrypted=await encryptWithPassphrase('support-reminder',input); await api('/v1/consents',{method:'POST',body:JSON.stringify({scope:'cycle'})}); await api('/v1/cycle/entry',{method:'POST',body:JSON.stringify({dataCiphertext:JSON.stringify(encrypted),sharedWithPartner:enabled})}); Alert.alert('ذخیره شد','داده‌ی حمایتی به‌صورت رمزگذاری‌شده ذخیره شد.'); setInput(''); }
   else if(feature==='music'){ const uri=input.trim(); if(!uri)throw new Error('Spotify track URI را وارد کن'); await api('/v1/playback',{method:'POST',body:JSON.stringify({trackUri:uri,isPlaying:true,positionMs:0})}); Alert.alert('اتاق موسیقی','وضعیت پخش مشترک ثبت شد. برای کنترل Spotify باید OAuth هر دو نفر را تکمیل کنیم.'); setInput(''); }
   else if(feature==='check-in'){ if(!input.trim())throw new Error('پاسخ را بنویس'); Alert.alert('ذخیره شد','پاسخ دوره‌ای برای فضای مشترک آماده شد.'); setInput(''); }
 }catch(error){Alert.alert('خطا',error instanceof Error?error.message:'عملیات ناموفق');}finally{setBusy(false);} };
 const stopLocation=async()=>{await api('/v1/location/stop',{method:'POST'}).catch(()=>{});await api('/v1/consents/location',{method:'DELETE'}).catch(()=>{});setEnabled(false);Alert.alert('متوقف شد','اشتراک‌گذاری موقعیت قطع شد.');};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ بازگشت</Text></Pressable><Text style={s.icon}>{meta.icon}</Text><Text style={s.title}>{meta.title}</Text><Text style={s.subtitle}>{meta.subtitle}</Text>
 {feature==='events'&&<><Card title="رویدادهای بعدی" body={items.length?items.slice(0,4).map(e=>`${e.title} · ${new Date(e.starts_at).toLocaleString()}`).join('\n'):'هنوز رویدادی ثبت نشده است.'}/><TextInput value={input} onChangeText={setInput} placeholder="عنوان رویداد برای فردا" placeholderTextColor={theme.colors.muted} style={s.input}/><Button label="افزودن رویداد" onPress={action}/></>}
 {feature==='ratings'&&<><Card title="حس این روزها" body="امتیاز رابطه فقط وقتی معتبر می‌شود که هر دو نفر به اندازه کافی بازخورد داده باشند."/>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setScore(n)} style={[s.option,score===n&&s.selected]}><Text style={s.optionText}>{n} · {['نیازمند توجه','کمی سخت','متوسط','خوب','خیلی خوب'][n-1]}</Text></Pressable>)}<Button label="ثبت بازخورد" onPress={action}/></>}
 {feature==='activities'&&<><Card title="پیشنهاد" body="یک غذای جدید را با هم درست کنید و گوشی‌ها را تا آخر شب کنار بگذارید."/><TextInput value={input} onChangeText={setInput} placeholder="ایده خودتان" placeholderTextColor={theme.colors.muted} style={s.input}/><Button label="ذخیره ایده" onPress={action}/></>}
 {feature==='music'&&<><Card title="Shared playback" body="Track URI را وارد کن؛ وضعیت پخش بین دو دستگاه به‌صورت مشترک ذخیره می‌شود."/><TextInput value={input} onChangeText={setInput} placeholder="spotify:track:..." placeholderTextColor={theme.colors.muted} style={s.input}/><Button label="شروع پخش مشترک" onPress={action}/></>}
 {feature==='location'&&<View style={s.card}><View style={s.consentHead}><Text style={s.cardTitle}>اشتراک موقعیت برای یک ساعت</Text><Switch value={enabled} onValueChange={v=>v?action():stopLocation()} trackColor={{true:theme.colors.primary}}/></View><Text style={s.body}>وقتی فعال است، فقط آخرین موقعیت قابل مشاهده است و با پایان زمان منقضی می‌شود.</Text>{enabled&&<Button label="توقف فوری" onPress={stopLocation} secondary/>}</View>}
 {feature==='wellbeing'&&<><Card title="داده خصوصی" body="این بخش نباید برای امتیاز رابطه، تنبیه یا کنترل استفاده شود."/><TextInput value={input} onChangeText={setInput} secureTextEntry placeholder="رمز محلی برای رمزگذاری" placeholderTextColor={theme.colors.muted} style={s.input}/><View style={s.card}><View style={s.consentHead}><Text style={s.cardTitle}>اشتراک با پارتنر</Text><Switch value={enabled} onValueChange={setEnabled}/></View><Text style={s.body}>اطلاعات فقط در صورت انتخاب تو قابل اشتراک است.</Text></View><Button label="ذخیره امن" onPress={action}/></>}
 {feature==='check-in'&&<><Card title="این هفته" body="یک چیز که پارتنرت انجام داد و باعث شد احساس قدردانی کنی چیست؟"/><TextInput value={input} onChangeText={setInput} multiline placeholder="پاسخت…" placeholderTextColor={theme.colors.muted} style={[s.input,s.area]}/><Button label="ذخیره پاسخ" onPress={action}/></>}
 </ScrollView></SafeAreaView>;
}
function Card({title,body}:{title:string;body:string}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text><Text style={s.body}>{body}</Text></View>;}
function Button({label,onPress,secondary}:{label:string;onPress:()=>void;secondary?:boolean}){return <Pressable style={[s.button,secondary&&s.secondary]} onPress={onPress}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{label}</Text></Pressable>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},content:{padding:22,paddingTop:18,paddingBottom:42},back:{color:theme.colors.primary,fontWeight:'800',fontSize:14},icon:{fontSize:34,marginTop:28},title:{color:theme.colors.text,fontSize:31,fontWeight:'900',marginTop:10},subtitle:{color:theme.colors.muted,fontSize:15,lineHeight:22,marginTop:6,marginBottom:22},card:{backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:theme.radius.md,padding:18,marginBottom:13},cardTitle:{color:theme.colors.text,fontSize:17,fontWeight:'800'},body:{color:theme.colors.muted,fontSize:13,lineHeight:20,marginTop:8},input:{backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:theme.radius.md,padding:15,color:theme.colors.text,fontSize:15,marginBottom:13},area:{height:130,textAlignVertical:'top'},button:{backgroundColor:theme.colors.primary,borderRadius:theme.radius.md,padding:16,alignItems:'center',marginBottom:10},buttonText:{color:'#fff',fontSize:15,fontWeight:'900'},secondary:{backgroundColor:theme.colors.background,borderWidth:1,borderColor:theme.colors.border},secondaryText:{color:theme.colors.text},option:{borderRadius:theme.radius.md,padding:15,backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,marginBottom:9},selected:{backgroundColor:'#4C1121',borderColor:theme.colors.primary},optionText:{color:theme.colors.text,fontWeight:'700'},consentHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}});
