import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { theme } from '../src/theme';
import type { MessageKind } from '../src/types/domain';
const labels: Record<MessageKind, string> = { normal: 'عادی', encrypted: 'رمزدار', time_capsule: 'کپسول زمان' };
export default function MessagesScreen() {
  const [kind, setKind] = useState<MessageKind>('normal'); const [text, setText] = useState('');
  const helper = useMemo(() => kind === 'encrypted' ? 'برای خواندن این پیام، رمز مشترک لازم است.' : kind === 'time_capsule' ? 'این پیام تا زمان انتخاب‌شده بسته می‌ماند.' : 'این پیام در فضای مشترک شما قرار می‌گیرد.', [kind]);
  const send = () => { if (!text.trim()) return; Alert.alert('آماده‌ی ارسال', `پیام ${labels[kind]} ذخیره شد. با اتصال بک‌اند امن، برای طرف مقابل ارسال می‌شود.`); setText(''); };
  return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={() => router.back()}><Text style={s.back}>›</Text></Pressable><View><Text style={s.title}>پیام‌ها</Text><Text style={s.sub}>یک یادداشت خصوصی برای عزیزت</Text></View></View><View style={s.body}><Text style={s.label}>نوع پیام</Text><View style={s.types}>{(Object.keys(labels) as MessageKind[]).map(value => <Pressable key={value} onPress={() => setKind(value)} style={[s.pill, kind === value && s.pillActive]}><Text style={[s.pillText, kind === value && s.pillTextActive]}>{labels[value]}</Text></Pressable>)}</View><TextInput accessibilityLabel="پیام" value={text} onChangeText={setText} multiline placeholder="یک پیام از دل بنویس…" placeholderTextColor={theme.colors.muted} style={s.input}/><Text style={s.helper}>{helper}</Text><Pressable style={s.send} onPress={send}><Text style={s.sendText}>ارسال پیام</Text></Pressable></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},header:{flexDirection:'row',alignItems:'center',gap:13,padding:22,paddingTop:20,borderBottomColor:theme.colors.border,borderBottomWidth:1},back:{color:theme.colors.text,fontSize:40,lineHeight:34},title:{color:theme.colors.text,fontSize:25,fontWeight:'800'},sub:{color:theme.colors.muted,fontSize:12,marginTop:2},body:{padding:22},label:{color:theme.colors.muted,fontWeight:'800',fontSize:10,letterSpacing:1.4},types:{flexDirection:'row',gap:8,marginTop:12,flexWrap:'wrap'},pill:{borderRadius:20,paddingVertical:10,paddingHorizontal:13,backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border},pillActive:{backgroundColor:'#4C1121',borderColor:theme.colors.primary},pillText:{color:theme.colors.muted,fontWeight:'700',fontSize:12},pillTextActive:{color:'#FDA4AF'},input:{height:180,marginTop:24,backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:theme.radius.md,padding:16,color:theme.colors.text,fontSize:16,textAlignVertical:'top'},helper:{color:theme.colors.muted,fontSize:12,lineHeight:18,marginTop:10},send:{backgroundColor:theme.colors.primary,alignItems:'center',padding:16,borderRadius:theme.radius.md,marginTop:26},sendText:{color:'#fff',fontWeight:'800',fontSize:16}});
