import { createCipheriv, createHash, randomBytes } from 'crypto';
import type { Express, Request, Response, NextFunction } from 'express';
import type { Pool } from 'pg';
import { z } from 'zod';

type AuthedRequest = Request & { userId?: string };
type AuthMiddleware = (req: AuthedRequest, res: Response, next: NextFunction) => void;

function base64url(value: Buffer) { return value.toString('base64url'); }
function config() { return z.object({ SPOTIFY_CLIENT_ID:z.string().min(1), SPOTIFY_REDIRECT_URI:z.string().url(), SPOTIFY_TOKEN_KEY:z.string().min(16) }).parse(process.env); }
function key(secret:string){ return createHash('sha256').update(secret).digest(); }
function seal(value:string, secret:string){ const iv=randomBytes(12); const cipher=createCipheriv('aes-256-gcm',key(secret),iv); const data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]); const tag=cipher.getAuthTag(); return [iv.toString('base64url'),tag.toString('base64url'),data.toString('base64url')].join('.'); }

function verifier(){ return base64url(randomBytes(64)).slice(0,96); }
function challenge(v:string){ return base64url(createHash('sha256').update(v).digest()); }

async function coupleFor(pool:Pool,userId:string){ const result=await pool.query<{couple_id:string}>('select couple_id from couple_members where user_id=$1 limit 1',[userId]); return result.rows[0]?.couple_id??null; }

export function attachSpotifyRoutes(app:Express,pool:Pool,requireAuth:AuthMiddleware){
  app.get('/v1/spotify/authorize',requireAuth,async(req:AuthedRequest,res,next)=>{try{const cfg=config();const v=verifier();const state=base64url(randomBytes(24));await pool.query('insert into spotify_oauth_states(state,user_id,code_verifier,expires_at) values($1,$2,$3,now()+interval \'10 minutes\')',[state,req.userId,v]);const params=new URLSearchParams({response_type:'code',client_id:cfg.SPOTIFY_CLIENT_ID,redirect_uri:cfg.SPOTIFY_REDIRECT_URI,state,scope:'user-read-playback-state user-modify-playback-state playlist-read-private playlist-modify-private playlist-modify-public',code_challenge_method:'S256',code_challenge:challenge(v)});res.json({authorizationUrl:`https://accounts.spotify.com/authorize?${params.toString()}`});}catch(e){next(e);}});
  app.get('/v1/spotify/callback',async(req,res,next)=>{try{const cfg=config();const input=z.object({code:z.string().min(1),state:z.string().min(1),error:z.string().optional()}).parse(req.query);if(input.error)return res.redirect('relationshiptracker://spotify-callback?status=error');const found=await pool.query<{user_id:string;code_verifier:string}>('select user_id,code_verifier from spotify_oauth_states where state=$1 and expires_at>now()',[input.state]);if(!found.rows[0])return res.status(400).send('Invalid or expired Spotify authorization state.');const tokenResponse=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:cfg.SPOTIFY_CLIENT_ID,grant_type:'authorization_code',code:input.code,redirect_uri:cfg.SPOTIFY_REDIRECT_URI,code_verifier:found.rows[0].code_verifier}).toString()});const tokens=await tokenResponse.json() as {access_token?:string;refresh_token?:string;expires_in?:number};if(!tokenResponse.ok||!tokens.access_token||!tokens.refresh_token)return res.status(502).send('Spotify token exchange failed.');const profileResponse=await fetch('https://api.spotify.com/v1/me',{headers:{Authorization:`Bearer ${tokens.access_token}`}});const profile=await profileResponse.json() as {id?:string};const coupleId=await coupleFor(pool,found.rows[0].user_id);if(!coupleId||!profile.id)return res.status(400).send('Connect to a couple before connecting Spotify.');await pool.query('insert into spotify_connections(couple_id,user_id,access_token_ciphertext,refresh_token_ciphertext,expires_at,spotify_user_id) values($1,$2,$3,$4,now()+($5 * interval \'1 second\'),$6) on conflict(couple_id,user_id) do update set access_token_ciphertext=excluded.access_token_ciphertext,refresh_token_ciphertext=excluded.refresh_token_ciphertext,expires_at=excluded.expires_at,spotify_user_id=excluded.spotify_user_id',[coupleId,found.rows[0].user_id,seal(tokens.access_token,cfg.SPOTIFY_TOKEN_KEY),seal(tokens.refresh_token,cfg.SPOTIFY_TOKEN_KEY),tokens.expires_in??3600,profile.id]);await pool.query('delete from spotify_oauth_states where state=$1',[input.state]);res.redirect('relationshiptracker://spotify-callback?status=ok');}catch(e){next(e);}});
  app.get('/v1/spotify/status',requireAuth,async(req:AuthedRequest,res,next)=>{try{const coupleId=await coupleFor(pool,req.userId!);if(!coupleId)return res.status(400).json({error:'not_paired'});const result=await pool.query('select spotify_user_id,expires_at from spotify_connections where couple_id=$1 and user_id=$2',[coupleId,req.userId]);res.json({connected:!!result.rows[0],connection:result.rows[0]??null});}catch(e){next(e);}});
}
